# Тема 3. Введення в Pandas та створення DataFrame

приклад 1: виведемо словник

In [5]:
client_info = {
    "name": "Andriy",
    "age": 30,
    "address": {
                "street": "Hlova Street, 10", 
                "city": "Kyiv", 
                "country": "Ukraine"},
    "email": "andriy@example.com",
    "phone": "+380123456789",
    "orders": [
                {"id": 1, "item_id": 55},
                {"id": 2, "item_id": 57},
                {"id": 3, "item_id": 587},
    ],
}
client_info
# часто будете працювати якщо дані з API, але частіше будуть дата інженери так отримувати дані

{'name': 'Andriy',
 'age': 30,
 'address': {'street': 'Hlova Street, 10',
  'city': 'Kyiv',
  'country': 'Ukraine'},
 'email': 'andriy@example.com',
 'phone': '+380123456789',
 'orders': [{'id': 1, 'item_id': 55},
  {'id': 2, 'item_id': 57},
  {'id': 3, 'item_id': 587}]}

In [6]:
# кожен ключ з нового рядка і відступи на рівні - для цього базова бібліотека json
# в ній є функція dumbs - словник в текст з форматуванням переводить

import json

dict_to_print =json.dumps(client_info)
print(dict_to_print)

{"name": "Andriy", "age": 30, "address": {"street": "Hlova Street, 10", "city": "Kyiv", "country": "Ukraine"}, "email": "andriy@example.com", "phone": "+380123456789", "orders": [{"id": 1, "item_id": 55}, {"id": 2, "item_id": 57}, {"id": 3, "item_id": 587}]}


Щоб вивести вміст словника в форматованому вигляді з нового рядка для кожного ключа та з відступами, потрібно використовувати аргументи indent та sort_keys у функції json.dumps. Ці аргументи дозволяють вказати рівень відступів та чи потрібно сортувати ключі у виведеному JSON.

- indent визначає кількість пробілів, які використовуються для відступів. Наприклад, indent=4 зробить відступ у чотири пробіли для кожного рівня вкладеності.
- sort_keys при значенні True впорядковує ключі словника за алфавітом.
Ось приклад використання цих параметрів:

In [7]:
# Використання json.dumps з indent і sort_keys
dict_to_print = json.dumps(client_info, indent=4, sort_keys=True)
print(dict_to_print)

{
    "address": {
        "city": "Kyiv",
        "country": "Ukraine",
        "street": "Hlova Street, 10"
    },
    "age": 30,
    "email": "andriy@example.com",
    "name": "Andriy",
    "orders": [
        {
            "id": 1,
            "item_id": 55
        },
        {
            "id": 2,
            "item_id": 57
        },
        {
            "id": 3,
            "item_id": 587
        }
    ],
    "phone": "+380123456789"
}


приклад 2: нам треба константа чиста Пі

In [8]:
from math import pi # спосіб імпортувати конкретну функцію з модуля

print(pi)

3.141592653589793


приклад 3: до кожного елементу масива додати 5

In [10]:
my_list = [1, 2, 3, 4, 5]
#my_list +5 # не можна додати число до списку

# але можна додати число до кожного елементу списку за допомогою
new_list = [] 
for x in my_list:
    new_list.append(x + 5)
print(new_list)

[6, 7, 8, 9, 10]


In [ ]:
# або можна використати бібліотеку numpy, що дозволяє виконувати операції над матрицями і векторами 

In [ ]:
# бібліотек в пайтоні доволі багато  - вони допомагають вирішувати різні задачі
# іноді вони вбудовані в пайтон, а іноді потрібно встановлювати окремо
# наприклад, для роботи з датами потрібно встановити бібліотеку datetime
# для роботи з графіками - matplotlib
# для роботи з даними - pandas
# для роботи з нейронними мережами - tensorflow
# для роботи з образами - opencv
# для роботи з текстами - nltk
# для роботи зі звуком - librosa
# для роботи з геоданими - geopandas
# іх треба перевіряти перед інсталяцією на ресурсі pypi.org - там є документація і приклади використання і статистка використання 

# I. NumPy

# pip install numpy

In [5]:
import numpy as np

# 1. Інструкція import в мові програмування Python використовується для підключення модулів та бібліотек до поточного скрипта.
# 2. Ми скорочуємо імпортоване ім'я до np для кращого читання коду за допомогою NumPy. Це широко розповсюджена угода, якій необхідно слідувати, щоб будь-хто, хто працює з нашим кодом, зміг легко його зрозуміти.
# 3. Інструкція from ... import використовується для імпортування конкретних імен з модуля. Це може бути корисно, якщо ви знаєте, які функції вам потрібні, і ви не хочете завантажувати весь модуль в пам'ять.

In [ ]:
# бібліотека NumPy - це основна бібліотека для наукових обчислень у Python.

# Об'єкт ndarray в NumPy -  це  ключовий об'єкт у бібліотеці NumPy.
# ndarray є скороченням від "n-dimensional array", що означає "багатовимірний масив".
# Це основний тип даних, який використовується в NumPy для зберігання і обробки багатовимірних масивів.
# ndarray не є вбудованим типом даних у Python, як, наприклад, int, float, або list.
# Натомість, ndarray є типом, який надається бібліотекою NumPy, спеціалізованою бібліотекою для наукових обчислень у Python.

# np.array - це функція в NumPy, яка використовується для створення нових об'єктів ndarray.
# Коли ви створюєте масив за допомогою np.array, ви отримуєте екземпляр ndarray.

Найпростіший спосіб створення невеликого масиву NumPy – виклик конструктора np.array зі списком або кортежем значень:

In [11]:
import numpy as np # стандартний еліас для numpy - np
# create a 1D array from a list
a = np.array([1, 2, 3, 4, 5], dtype=float)

print(a)  # [1. 2. 3. 4. 5.]
a+5

[1. 2. 3. 4. 5.]


array([ 6.,  7.,  8.,  9., 10.])

In [13]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
# create a 2d array
m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

print(m)

[[1 2 3]
 [4 5 6]]


## Atributes

In [16]:
import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)


m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

# Розмірність створеного вектора та матриці можна подивитися за допомогою атрибуту shape.Розмірність - це кортеж, який містить кількість елементів у кожному розмірі масиву.
print(a.shape)  # (5,)
print(m.shape)  # (2, 3)

# size - це атрибут, який містить загальну кількість елементів у масиві.
print(a.size)
print(m.size)

# dtype - це атрибут, який містить тип даних, який зберігається в масиві.
print(a.dtype)
print(m.dtype)

(5,)
(2, 3)
5
6
float64
int64


In [18]:
# Щоб створити масив з випадковими числами, використовуйте функцію random.
import numpy as np

a = np.random.random(3) # 3 випадкових числа від 0 до 1
b = np.random.random((3, 3)) # 3 випадкових числа від 0 до 1
print(a , '\n')
print(b)

[0.11997659 0.02658034 0.44782431] 

[[0.07873519 0.84684936 0.7125563 ]
 [0.25744043 0.28948772 0.46465809]
 [0.66468088 0.67163968 0.39712495]]


In [5]:
# Щоб створити масив з одиниць, використовуйте функцію ones.
import numpy as np

a = np.ones((5,), dtype=float)
print(a)

m = np.ones((2, 3), dtype=int)
print(m)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [ ]:
# Щоб створити масив з нулів, використовуйте функцію zeros.
import numpy as np

a = np.zeros(5, dtype=float)
print(a)

m = np.zeros((2, 3), dtype=int)
print(m)

In [6]:
# Щоб створити одиничну матрицю, використовуйте функцію eye.
m = np.identity(4, dtype=int)
print(m)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [8]:
# Щоб створити масив з послідовністю чисел, використовуйте функцію arange.
import numpy as np

a = np.arange(5) # 5 послідовних чисел починаючи з 0
b = np.arange(1, 3, 0.5) # послідовність чисел від 1 до 3 з кроком 0.5
print(a)
print(b)

[0 1 2 3 4]
[1.  1.5 2.  2.5]


In [11]:
# Щоб створити масив з рівномірно розподіленими числами, використовуйте функцію linspace. 
# Ця функція приймає три аргументи: початок послідовності, кінець послідовності, кількість елементів.
# По замовчуванню кількість елементів дорівнює 50.
import numpy as np

a = np.linspace(1, 5, num=5) # 5 рівномірно розподілених чисел від 1 до 5
b = np.linspace(1, 3, num=3) # 3 рівномірно розподілених чисел від 1 до 3
print(a)
print(b)

[1. 2. 3. 4. 5.]
[1. 2. 3.]


### Індексація / Slising 

In [21]:
# Масив NumPy можна розділити на частини та присвоїти їм індекси. Принцип роботи схожий на те, як це відбувається зі списками Python.

import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[0]) # перший елемент
print(a[1:]) # з другого елемента до кінця
print(a[:2]) # з початку до другого елемента

1
[2 3 4 5]
[1 2]


Індексація багатовимірного масиву NumPy трохи відрізняється від індексації звичайного списку списків у Python: замість зазначення індексу необхідного елемента в окремих квадратних дужках m[i][j] використовується кортеж цілих чисел m[i, j]:

In [25]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a[0])     # перший рядок
print(a[0][0:2])  # перший рядок, перші два елементи
print(a[0][0])  # перший рядок, перший елемент
print('\n')
print(a[1, 1]) # другий рядок, другий елемент
print(a[1:, 1]) # з другого рядка, другий елемент
print(a[0, :2]) # перший рядок, перші два елементи

[1 2 3]
[1 2]
1


5
[5 8]
[1 2]


In [26]:
# за індексом можна задати елемент масива 
print(a)
a[0, 0] = 10
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## Арифметичні операції



In [28]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
trip_arr = a * 3
print(trip_arr)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [29]:
float_arr = a.astype(float) # змінює тип даних на float
print(float_arr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Basic math

In [38]:
# При арифметичних операціях не потрібне написання циклів for з обчисленнями. Операції над масивами виконуються для кожного ряду.

import numpy as np

a = np.random.random(10)
b = np.random.random(10)

print(a, "\n")
print(b, "\n")
print(a + b, "\n")
print(a - b, "\n")
print(a * b, "\n")
print(a / b, "\n")

[0.56822696 0.70443213 0.95263174 0.7465049  0.78239772 0.49061047
 0.97500655 0.74411134 0.91628865 0.51910735] 

[0.11263428 0.94273771 0.38565862 0.08674395 0.89896821 0.59486776
 0.30794086 0.62208476 0.91719475 0.23464407] 

[0.68086124 1.64716984 1.33829037 0.83324885 1.68136593 1.08547823
 1.28294741 1.3661961  1.83348339 0.75375142] 

[ 0.45559268 -0.23830558  0.56697312  0.65976094 -0.11657048 -0.10425729
  0.66706569  0.12202658 -0.0009061   0.28446329] 

[0.06400183 0.66409473 0.36739065 0.06475479 0.70335068 0.29184835
 0.30024435 0.46290032 0.84041513 0.12180546] 

[5.04488476 0.74721963 2.47014248 8.60584365 0.87032858 0.82473871
 3.16621364 1.19615749 0.99901209 2.21231828] 



In [39]:
add = np.add(a, b)
sub = np.subtract(a, b)
mul = np.multiply(a, b)
div = np.divide(a, b)

print(add, "\n")
print(sub, "\n")
print(mul, "\n")
print(div, "\n")

[0.68086124 1.64716984 1.33829037 0.83324885 1.68136593 1.08547823
 1.28294741 1.3661961  1.83348339 0.75375142] 

[ 0.45559268 -0.23830558  0.56697312  0.65976094 -0.11657048 -0.10425729
  0.66706569  0.12202658 -0.0009061   0.28446329] 

[0.06400183 0.66409473 0.36739065 0.06475479 0.70335068 0.29184835
 0.30024435 0.46290032 0.84041513 0.12180546] 

[5.04488476 0.74721963 2.47014248 8.60584365 0.87032858 0.82473871
 3.16621364 1.19615749 0.99901209 2.21231828] 



In [3]:
# Якщо розміри масивів не співпадають, то виконується операція над кожним рядом.
# Якщо розміри масивів не співпадають, але можуть бути розширені (Арифметичні операції над матрицями різних розмірів можливі в тому випадку, якщо одна з матриць має лише один стовпець або один рядок.)
# то розмір результуючого масиву буде рівний розміру більшого масиву.

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 2, 3])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[0 0 0]
 [3 3 3]
 [6 6 6]]
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[[1.  1.  1. ]
 [4.  2.5 2. ]
 [7.  4.  3. ]]


Якщо розміри масивів не співпадають і не можуть бути розширені, то виникає помилка.

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 2, 3], [4, 5, 6]])
print(a + b)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[11], line 1
----> 1 print(a + b)

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [50]:
# Матричне множення:
# Щоб виконати звичайне математичне множення матриць, використовують функцію numpy.dot() або оператор @.
# Це відповідає стандартному математичному множенню матриць, де рядки однієї матриці множаться на стовпці іншої.
# матриця B має мати стільки ж рядків, скільки стовпців у матриці і на виході буде матриця з таким же розміром
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])
c = np.dot(a,b)  # або c = a @ b
print(c)

[[22 28]
 [49 64]]


# Stat Functions

In [42]:
a = np.random.random(10)
b = np.random.random(10)

print(a, "\n")
print(b, "\n")

sqrt_arr = np.sqrt(25)
abs_arr = np.abs(-25)
power_arr = np.power(5, 2)
mins = a.min()
maxs = a.max()

print(mins, "\n")

[0.44449057 0.08883863 0.82480698 0.98604529 0.14480099 0.60280905
 0.35233946 0.35061104 0.33197799 0.10173767] 

[0.64754507 0.90337074 0.13753133 0.82971503 0.55996676 0.41094332
 0.06471947 0.02717994 0.82712942 0.81096757] 

0.08883862750380045 



# Sorting

In [43]:
a = np.random.random(10)
print(a, "\n")
a.sort()
print(a, "\n")

[0.53194203 0.93788867 0.01145605 0.2069125  0.06366099 0.31409938
 0.75819315 0.20470702 0.1203253  0.85307433] 

[0.01145605 0.06366099 0.1203253  0.20470702 0.2069125  0.31409938
 0.53194203 0.75819315 0.85307433 0.93788867] 



In [45]:
# у зворотньому порядку
a = np.random.random(10)
print(a, "\n")

a.sort()  # Спочатку сортуємо список
reversed_a = a[::-1]  # Потім звертаємо його.# зворотній порядок бо -1 (Тут : означає взяти весь список, а -1 вказує, що крок перебору елементів має бути задом наперед.)
print(reversed_a, "\n")

[0.2851831  0.87294029 0.83057127 0.42185866 0.63159829 0.79622046
 0.09826748 0.48920009 0.47543572 0.47395984] 

[0.87294029 0.83057127 0.79622046 0.63159829 0.48920009 0.47543572
 0.47395984 0.42185866 0.2851831  0.09826748] 



In [46]:
reversed_a = sorted(a, reverse=True)
print(reversed_a, "\n")

[0.8729402923953556, 0.8305712686690464, 0.7962204590169327, 0.6315982894838983, 0.4892000907638143, 0.47543571714642974, 0.4739598425495093, 0.4218586643638782, 0.28518309878852144, 0.09826747771076916] 

