# Тема 3. Введення в Pandas та створення DataFrame

приклад 1: виведемо словник

In [ ]:
import numpy as np
import json
from math import pi  # спосіб імпортувати конкретну функцію з модуля

In [51]:
client_info = {
    "name": "Andriy",
    "age": 30,
    "address": {
                "street": "Hlova Street, 10", 
                "city": "Kyiv", 
                "country": "Ukraine"},
    "email": "andriy@example.com",
    "phone": "+380123456789",
    "orders": [
                {"id": 1, "item_id": 55},
                {"id": 2, "item_id": 57},
                {"id": 3, "item_id": 587},
    ],
}
client_info
# часто будете працювати якщо дані з API, але частіше будуть дата інженери так отримувати дані

{'name': 'Andriy',
 'age': 30,
 'address': {'street': 'Hlova Street, 10',
  'city': 'Kyiv',
  'country': 'Ukraine'},
 'email': 'andriy@example.com',
 'phone': '+380123456789',
 'orders': [{'id': 1, 'item_id': 55},
  {'id': 2, 'item_id': 57},
  {'id': 3, 'item_id': 587}]}

In [52]:
# кожен ключ з нового рядка і відступи на рівні - для цього базова бібліотека json
# в ній є функція dumbs - словник в текст з форматуванням переводить

import json

dict_to_print =json.dumps(client_info)
print(dict_to_print)

{"name": "Andriy", "age": 30, "address": {"street": "Hlova Street, 10", "city": "Kyiv", "country": "Ukraine"}, "email": "andriy@example.com", "phone": "+380123456789", "orders": [{"id": 1, "item_id": 55}, {"id": 2, "item_id": 57}, {"id": 3, "item_id": 587}]}


Щоб вивести вміст словника в форматованому вигляді з нового рядка для кожного ключа та з відступами, потрібно використовувати аргументи indent та sort_keys у функції json.dumps. Ці аргументи дозволяють вказати рівень відступів та чи потрібно сортувати ключі у виведеному JSON.

- indent визначає кількість пробілів, які використовуються для відступів. Наприклад, indent=4 зробить відступ у чотири пробіли для кожного рівня вкладеності.
- sort_keys при значенні True впорядковує ключі словника за алфавітом.
Ось приклад використання цих параметрів:

In [53]:
# Використання json.dumps з indent і sort_keys
dict_to_print = json.dumps(client_info, indent=4, sort_keys=True)
print(dict_to_print)

{
    "address": {
        "city": "Kyiv",
        "country": "Ukraine",
        "street": "Hlova Street, 10"
    },
    "age": 30,
    "email": "andriy@example.com",
    "name": "Andriy",
    "orders": [
        {
            "id": 1,
            "item_id": 55
        },
        {
            "id": 2,
            "item_id": 57
        },
        {
            "id": 3,
            "item_id": 587
        }
    ],
    "phone": "+380123456789"
}


приклад 2: нам треба константа чиста Пі

In [55]:
from math import pi # спосіб імпортувати конкретну функцію з модуля

print(pi)

3.141592653589793


приклад 3: до кожного елементу масива додати 5

In [59]:
my_list = [1, 2, 3, 4, 5]
print(my_list)

#my_list + 5 # не можна додати число до списку

[1, 2, 3, 4, 5]


In [60]:
# але можна додати число до кожного елементу списку за допомогою
new_list = [] 
for x in my_list:
    new_list.append(x + 5)
print(new_list)

[6, 7, 8, 9, 10]


In [ ]:
# або можна використати бібліотеку numpy, що дозволяє виконувати операції над матрицями і векторами 

In [ ]:
# бібліотек в пайтоні доволі багато  - вони допомагають вирішувати різні задачі
# іноді вони вбудовані в пайтон, а іноді потрібно встановлювати окремо
# наприклад, для роботи з датами потрібно встановити бібліотеку datetime
# для роботи з графіками - matplotlib
# для роботи з даними - pandas
# для роботи з нейронними мережами - tensorflow
# для роботи з образами - opencv
# для роботи з текстами - nltk
# для роботи зі звуком - librosa
# для роботи з геоданими - geopandas
# іх треба перевіряти перед інсталяцією на ресурсі pypi.org - там є документація і приклади використання і статистка використання 

# I. NumPy

# pip install numpy

In [61]:
import numpy as np

# 1. Інструкція import в мові програмування Python використовується для підключення модулів та бібліотек до поточного скрипта.
# 2. Ми скорочуємо імпортоване ім'я до np для кращого читання коду за допомогою NumPy. Це широко розповсюджена угода, якій необхідно слідувати, щоб будь-хто, хто працює з нашим кодом, зміг легко його зрозуміти.
# 3. Інструкція from ... import використовується для імпортування конкретних імен з модуля. Це може бути корисно, якщо ви знаєте, які функції вам потрібні, і ви не хочете завантажувати весь модуль в пам'ять.

In [ ]:
# бібліотека NumPy - це основна бібліотека для наукових обчислень у Python.

# Об'єкт ndarray в NumPy -  це  ключовий об'єкт у бібліотеці NumPy.
# ndarray є скороченням від "n-dimensional array", що означає "багатовимірний масив".
# Це основний тип даних, який використовується в NumPy для зберігання і обробки багатовимірних масивів.
# ndarray не є вбудованим типом даних у Python, як, наприклад, int, float, або list.
# Натомість, ndarray є типом, який надається бібліотекою NumPy, спеціалізованою бібліотекою для наукових обчислень у Python.

# np.array - це функція в NumPy, яка використовується для створення нових об'єктів ndarray.
# Коли ви створюєте масив за допомогою np.array, ви отримуєте екземпляр ndarray.

Найпростіший спосіб створення невеликого масиву NumPy – виклик конструктора np.array зі списком або кортежем значень:

In [64]:
import numpy as np # стандартний еліас для numpy - np
# create a 1D array from a list
a = np.array([1, 2, 3, 4, 5], dtype=float)

print(a)  # [1. 2. 3. 4. 5.]
a+5

[1. 2. 3. 4. 5.]


array([ 6.,  7.,  8.,  9., 10.])

In [65]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [67]:
# create a 2d array
m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

print(m)

[[1 2 3]
 [4 5 6]]


## Atributes

In [70]:

a = np.array([1, 2, 3, 4, 5], dtype=float)
m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

# Розмірність створеного вектора та матриці можна подивитися за допомогою атрибуту shape.Розмірність - це кортеж, який містить кількість елементів у кожному розмірі масиву.
print(a.shape)  # (5,)
print(m.shape)  # (2, 3)

# size - це атрибут, який містить загальну кількість елементів у масиві.
print(a.size)
print(m.size)

# dtype - це атрибут, який містить тип даних, який зберігається в масиві.
print(a.dtype)
print(m.dtype)

(5,)
(2, 3)
5
6
float64
int64


In [73]:
# Щоб створити масив з випадковими числами, використовуйте функцію random.
import numpy as np

a = np.random.random(3) # 3 випадкових числа від 0 до 1
b = np.random.random((3, 3)) # 3 випадкових числа від 0 до 1
print(a , '\n')
print(b)

[0.83578357 0.09297304 0.09770802] 

[[1.83835250e-01 2.52974185e-01 7.73707011e-04]
 [8.27299218e-01 8.85430549e-01 6.74062244e-01]
 [9.63900792e-01 6.03126184e-01 1.38522655e-01]]


In [75]:
# Щоб створити масив з одиниць, використовуйте функцію ones.
import numpy as np

a = np.ones((5,), dtype=float)
print(a)

m = np.ones((2, 3), dtype=int)
print(m)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [76]:
# Щоб створити масив з нулів, використовуйте функцію zeros.
import numpy as np

a = np.zeros(5, dtype=float)
print(a)

m = np.zeros((2, 3), dtype=int)
print(m)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]


In [77]:
# Щоб створити одиничну матрицю, використовуйте функцію eye.
m = np.identity(4, dtype=int)
print(m)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [78]:
# Щоб створити масив з послідовністю чисел, використовуйте функцію arange.
import numpy as np

a = np.arange(5) # 5 послідовних чисел починаючи з 0
b = np.arange(1, 3, 0.5) # послідовність чисел від 1 до 3 з кроком 0.5
print(a)
print(b)

[0 1 2 3 4]
[1.  1.5 2.  2.5]


In [79]:
# Щоб створити масив з рівномірно розподіленими числами, використовуйте функцію linspace. 
# Ця функція приймає три аргументи: початок послідовності, кінець послідовності, кількість елементів.
# По замовчуванню кількість елементів дорівнює 50.
import numpy as np

a = np.linspace(1, 5, num=5) # 5 рівномірно розподілених чисел від 1 до 5
b = np.linspace(1, 3, num=3) # 3 рівномірно розподілених чисел від 1 до 3
print(a)
print(b)

[1. 2. 3. 4. 5.]
[1. 2. 3.]


### Індексація / Slising 

In [81]:
# Масив NumPy можна розділити на частини та присвоїти їм індекси. Принцип роботи схожий на те, як це відбувається зі списками Python.

import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[0]) # перший елемент
print(a[1:]) # з другого елемента до кінця
print(a[:2]) # з початку до другого елемента

1
[2 3 4 5]
[1 2]


Індексація багатовимірного масиву NumPy трохи відрізняється від індексації звичайного списку списків у Python: замість зазначення індексу необхідного елемента в окремих квадратних дужках m[i][j] використовується кортеж цілих чисел m[i, j]:

In [84]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a[0])     # перший рядок
print(a[0][0:2])  # перший рядок, перші два елементи
print(a[0][0])  # перший рядок, перший елемент
print('\n')
print(a[1, 1]) # другий рядок, другий елемент
print(a[1:, 1]) # з другого рядка, другий елемент
print(a[0, :2]) # перший рядок, перші два елементи

[1 2 3]
[1 2]
1


5
[5 8]
[1 2]


In [85]:
# за індексом можна задати елемент масива 
print(a)
a[0, 0] = 10
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## Арифметичні операції



In [88]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
trip_arr = a * 3
print(trip_arr)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [89]:
float_arr = a.astype(float) # змінює тип даних на float
print(float_arr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Basic math

In [90]:
# При арифметичних операціях не потрібне написання циклів for з обчисленнями. Операції над масивами виконуються для кожного ряду.

import numpy as np

a = np.random.random(10)
b = np.random.random(10)

print(a, "\n")
print(b, "\n")

print(a + b, "\n")
print(a - b, "\n")
print(a * b, "\n")
print(a / b, "\n")

[0.87112797 0.032603   0.93295568 0.75441056 0.91948053 0.00655292
 0.09974217 0.56512118 0.99494317 0.12762141] 

[0.35809352 0.72705581 0.95096836 0.43476337 0.120655   0.6927949
 0.38715951 0.3779894  0.57966981 0.84071148] 

[1.22922148 0.75965881 1.88392405 1.18917393 1.04013553 0.69934782
 0.48690168 0.94311058 1.57461299 0.96833289] 

[ 0.51303445 -0.69445282 -0.01801268  0.31964719  0.79882553 -0.68624198
 -0.28741734  0.18713178  0.41527336 -0.71309007] 

[0.31194528 0.0237042  0.88721134 0.32799008 0.11093992 0.00453983
 0.03861613 0.21360982 0.57673852 0.10729278] 

[2.43268288 0.0448425  0.9810586  1.73522107 7.62074128 0.00945867
 0.25762552 1.49507151 1.71639639 0.15180167] 



In [93]:
add = np.add(a, b)
sub = np.subtract(a, b)
mul = np.multiply(a, b)
div = np.divide(a, b)

print(add, "\n")
print(sub, "\n")
print(mul, "\n")
print(div, "\n")

[1.22922148 0.75965881 1.88392405 1.18917393 1.04013553 0.69934782
 0.48690168 0.94311058 1.57461299 0.96833289] 

[ 0.51303445 -0.69445282 -0.01801268  0.31964719  0.79882553 -0.68624198
 -0.28741734  0.18713178  0.41527336 -0.71309007] 

[0.31194528 0.0237042  0.88721134 0.32799008 0.11093992 0.00453983
 0.03861613 0.21360982 0.57673852 0.10729278] 

[2.43268288 0.0448425  0.9810586  1.73522107 7.62074128 0.00945867
 0.25762552 1.49507151 1.71639639 0.15180167] 



In [94]:
# Якщо розміри масивів не співпадають, то виконується операція над кожним рядом.
# Якщо розміри масивів не співпадають, але можуть бути розширені (Арифметичні операції над матрицями різних розмірів можливі в тому випадку, якщо одна з матриць має лише один стовпець або один рядок.)
# то розмір результуючого масиву буде рівний розміру більшого масиву.

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[0 0 0]
 [3 3 3]
 [6 6 6]]
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[[1.  1.  1. ]
 [4.  2.5 2. ]
 [7.  4.  3. ]]


Якщо розміри масивів не співпадають і не можуть бути розширені, то виникає помилка.

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 2, 3], [4, 5, 6]])
print(a + b)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[11], line 1
----> 1 print(a + b)

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [95]:
# Матричне множення:
# Щоб виконати звичайне математичне множення матриць, використовують функцію numpy.dot() або оператор @.
# Це відповідає стандартному математичному множенню матриць, де рядки однієї матриці множаться на стовпці іншої.
# матриця B має мати стільки ж рядків, скільки стовпців у матриці і на виході буде матриця з таким же розміром
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])

c = np.dot(a,b)  # або c = a @ b
print(c)

[[22 28]
 [49 64]]


# Stat Functions

In [97]:
a = np.random.random(10)
b = np.random.random(10)

print(a, "\n")
print(b, "\n")

sqrt_arr = np.sqrt(25)
abs_arr = np.abs(-25)
power_arr = np.power(5, 2)

mins = a.min()
maxs = a.max()

print(mins, "\n")

[0.8518019  0.6535514  0.89372806 0.20390288 0.69861136 0.92762968
 0.74500738 0.64962705 0.49323751 0.31809712] 

[0.30676819 0.8178632  0.06862255 0.33363026 0.30606523 0.31823828
 0.54885765 0.18350087 0.09510367 0.66972818] 

0.2039028839599336 



# Sorting

In [98]:
a = np.random.random(10)
print(a, "\n")

a.sort()
print(a, "\n")

[0.72296367 0.56755383 0.76887112 0.18808059 0.189684   0.04111643
 0.61107153 0.15916665 0.05883633 0.49748632] 

[0.04111643 0.05883633 0.15916665 0.18808059 0.189684   0.49748632
 0.56755383 0.61107153 0.72296367 0.76887112] 



In [100]:
# у зворотньому порядку
a = np.random.random(10)
print(a, "\n")

a.sort()  # Спочатку сортуємо список
reversed_a = a[::-1]  # Потім звертаємо його.# зворотній порядок бо -1 (Тут : означає взяти весь список, а -1 вказує, що крок перебору елементів має бути задом наперед.)
print(reversed_a, "\n")

[0.31800216 0.04239552 0.79190199 0.40822457 0.9168872  0.71971533
 0.77125465 0.62447733 0.17014459 0.95448577] 

[0.95448577 0.9168872  0.79190199 0.77125465 0.71971533 0.62447733
 0.40822457 0.31800216 0.17014459 0.04239552] 



In [101]:
reversed_a = sorted(a, reverse=True)
print(reversed_a, "\n")

[0.954485766116746, 0.916887198363519, 0.791901990974261, 0.7712546476418015, 0.7197153332454796, 0.6244773274036529, 0.408224573152139, 0.31800215631990614, 0.17014458882191674, 0.04239551554531462] 

